version: "3.8"

services:
  db:
    image: postgres:14
    container_name: club-db
    environment:
      POSTGRES_DB: club
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: club-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
